variable "access_key" {}
variable "secret_key" {}
variable "region" {}
variable "vpc_cidr" {}
variable "project" {}
variable "sn_cidr" {}
variable "az" {}
variable "ami" {}
variable "instance_type" {}